require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true

  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'lib/tasks/cucumber.rake'
    - 'lib/templates/**/*'
    - 'script/cucumber'
    - 'vendor/**/*'

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/EmptyLinesAroundArguments:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/**/*.rb'
    - 'factories/**/*.rb'
    - 'lib/capistrano/tasks/**/*.rake'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Exclude:
    - 'config/initializers/simple_form.rb'
    - 'config/initializers/simple_form_bootstrap.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'

Rails:
  Enabled: true

Rails/BulkChangeTable:
  Enabled: false

Rails/HasAndBelongsToMany:
  Exclude:
    - 'app/models/role.rb'

Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/application_controller.rb'

Rails/ReversibleMigration:
  Enabled: false

Rails/SkipsModelValidations:
  Whitelist:
    - update_all

Style/AndOr:
  EnforcedStyle: conditionals

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/policies/**/*.rb'
    - 'app/controllers/**/*.rb'

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - 'features/support/env.rb'
    - 'spec/spec_helper.rb'

Style/RescueModifier:
  Exclude:
    - 'spec/**/*.rb'

Style/Semicolon:
  Exclude:
    - 'spec/**/*.rb'

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
