AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true

  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/AlignHash:
  EnforcedColonStyle: table

Layout/EmptyLinesAroundArguments:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/initializers/*.rb'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Exclude:
    - 'config/initializers/simple_form.rb'
    - 'config/initializers/simple_form_bootstrap.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'

Rails:
  Enabled: true

Style/AndOr:
  EnforcedStyle: conditionals

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
