require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true

  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'lib/tasks/cucumber.rake'
    - 'lib/templates/**/*'
    - 'script/cucumber'
    - 'vendor/**/*'

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/EmptyLinesAroundArguments:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/**/*.rb'
    - 'db/migrate/*.rb'
    - 'factories/**/*.rb'
    - 'lib/capistrano/tasks/**/*.rake'
    - 'spec/**/*.rb'

Metrics/ClassLength:
  Exclude:
    - 'db/migrate/*.rb'

Metrics/LineLength:
  Exclude:
    - 'config/initializers/simple_form.rb'
    - 'config/initializers/simple_form_bootstrap.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'

Naming/PredicateName:
  Exclude:
    - 'app/models/application_record.rb'

Rails:
  Enabled: true

Rails/BulkChangeTable:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/application_controller.rb'

Rails/RakeEnvironment:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - 'development'
    - 'production'
    - 'staging'
    - 'test'

RSpec/ContextWording:
  Prefixes:
    - 'after'
    - 'for'
    - 'when'
    - 'with'
    - 'without'

RSpec/DescribeClass:
  Exclude:
    - 'spec/requests/**/*_spec.rb'

RSpec/ExampleLength:
  Max: 8

RSpec/ExpectInHook:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/ScatteredSetup:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/policies/**/*.rb'
    - 'app/controllers/**/*.rb'

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - 'features/support/env.rb'
    - 'spec/spec_helper.rb'

Style/RescueModifier:
  Exclude:
    - 'spec/**/*.rb'

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/Semicolon:
  Exclude:
    - 'spec/**/*.rb'

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
