default: &default
  host: <%= ENV.fetch('RAILS_CACHE_REDIS_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('RAILS_CACHE_REDIS_PORT') { 6379 } %>
  db:   <%= ENV.fetch('RAILS_CACHE_REDIS_DB') { 1 } %>

development:
  <<: *default
  password: <%= ENV.fetch('RAILS_CACHE_REDIS_PASSWORD') { 'password' } %>

production:
  <<: *default
  password: <%= Rails.application.credentials.rails_cache_redis_password %>
