#!/usr/bin/env ruby
# frozen_string_literal: true

require 'fileutils'

APP_ROOT = File.expand_path('..', __dir__).freeze

def system!(*args)
  system(*args) or abort "\n== Command #{args} failed =="
end

initial = !!ARGV.delete('--initial')

FileUtils.chdir APP_ROOT do
  puts '== Update RubyGems =='
  system! 'gem update --system'

  puts '== Update Bundler =='
  system! "gem install bundler -v '~> 2.0'"

  puts '== Installing gems =='
  system 'bin/bundle check' or system! 'bin/bundle install'

  puts '== Install JavaScript dependencies =='
  system! 'bin/rake yarn:install'

  if initial
    puts '== Preparing database =='
    system! 'bin/rails db:setup'
  else
    puts '== Updating database =='
    system! 'bin/rails db:migrate'
  end

  puts '== Removing old logs and tempfiles =='
  system! 'bin/rails log:clear tmp:clear'

  puts '== Restarting application server =='
  system! 'bin/rails restart'
end
