default: &default
  host:     <%= ENV.fetch('ELASTICSEARCH_HOST')     { 'localhost' } %>
  port:     <%= ENV.fetch('ELASTICSEARCH_PORT')     { 9200        } %>
  user:     <%= ENV.fetch('ELASTICSEARCH_USER')     { 'elastic'   } %>
  password: <%= ENV.fetch('ELASTICSEARCH_PASSWORD') { 'changeme'  } %>
  ssl:      false
  ssl_params:
    ca_file: null

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
