default: &default
  # Fully qualified domain name.
  site_domain: 'libertarian-party.com'

  # Email which all mail is sent from.
  noreply_email_address: 'no-reply@libertarian-party.com'
  noreply_email_contact: >-
    Libertarian party of Russia <no-reply@libertarian-party.com>

development:
  <<: *default

test:
  <<: *default

staging:
  site_domain: 'stg.libertarian-party.com'

  noreply_email_address: 'no-reply@stg.libertarian-party.com'
  noreply_email_contact: >-
    Libertarian party of Russia <no-reply@stg.libertarian-party.com>

production:
  <<: *default
